# Program the Nexys A7 with the bitstream generated by build_nexys_a7.tcl.
#
# Run from the repository root after building:
#   C:/AMDDesignTools/2025.2/Vivado/bin/vivado.bat -mode batch -source scripts/program_nexys_a7.tcl

set script_dir [file dirname [file normalize [info script]]]
set repo_root  [file normalize [file join $script_dir ".."]]
set bit_file   [file join $repo_root "build" "vivado" "trex_dino_nexys_a7.runs" "impl_1" "top_fpga.bit"]

if {![file exists $bit_file]} {
    error "Bitstream not found: $bit_file. Run scripts/build_nexys_a7.tcl first."
}

open_hw_manager
connect_hw_server

set targets [get_hw_targets *]
if {[llength $targets] == 0} {
    error "No hardware target found. Connect/power the Nexys A7 and ensure the Digilent USB-JTAG cable is visible."
}

current_hw_target [lindex $targets 0]
open_hw_target

set dev [lindex [get_hw_devices xc7a100t*] 0]
if {$dev eq ""} {
    error "No xc7a100t device found. Check the Nexys A7 USB/JTAG connection."
}

current_hw_device $dev
refresh_hw_device -update_hw_probes false $dev
set_property PROGRAM.FILE $bit_file $dev
program_hw_devices $dev

puts "Programmed $dev with $bit_file"
